[package]
name = "gpui-es-fluent-demo"
version = "0.1.0"
rust-version = "1.98"
edition = "2024"
license = "Unlicense"
publish = false
autobins = false

[[example]]
name = "demo"
path = "src/main.rs"

[dependencies]
es-fluent = { git = "https://github.com/stayhydated/es-fluent", rev = "4b900ddaebdc6d4335a6bcb15a610277b1b193f8", version = "0.18.1" }
es-fluent-manager-embedded = { git = "https://github.com/stayhydated/es-fluent", rev = "4b900ddaebdc6d4335a6bcb15a610277b1b193f8", version = "0.18.1" }
gpui = { branch = "linux-headless-renderer", git = "https://github.com/stayhydated/zed" }
gpui-component = { git = "https://github.com/stayhydated/gpui-component", rev = "cdba027283fec36e37fb4b90dea862b1e116aa2d" }
gpui-component-assets = { git = "https://github.com/stayhydated/gpui-component", rev = "cdba027283fec36e37fb4b90dea862b1e116aa2d" }
gpui-es-fluent = { features = [ "component" ], path = "../.." }
gpui_platform = { branch = "linux-headless-renderer", features = [
  "font-kit",
  "runtime_shaders",
  "wayland",
  "x11",
], git = "https://github.com/stayhydated/zed" }
wasm-bindgen = "0.2"

[lib]
crate-type = [ "cdylib", "rlib" ]

[build-dependencies]
es-fluent-build = { git = "https://github.com/stayhydated/es-fluent", rev = "4b900ddaebdc6d4335a6bcb15a610277b1b193f8", version = "0.18.1" }

[lints.rust]
future_incompatible = "deny"
nonstandard_style = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"
