[application]
asset_dir = "public"
name = "gpui-es-fluent"
out_dir = "dist"

[web.app]
base_path = "gpui-es-fluent"
title = "gpui-es-fluent"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = [ "src", "public" ]
